import {load} from "cheerio";
import type {RawBuybackItem} from "../../types.js";
import {compact,optional,positiveYen} from "../../shared/parser.js";
import {normalizeCondition} from "../../shared/normalization.js";

export function parseKaitori1Chome(html:string,baseUrl:string,fetchedAt:string):RawBuybackItem[]{const $=load(html),items:RawBuybackItem[]=[];$("[data-buyback-item], .buyback-item, .product-item").each((_index,element)=>{const row=$(element),productName=compact(row.find("[data-product-name], .product-name, .item-name").first().text()),price=positiveYen(row.find("[data-buyback-price], .buyback-price, .price").first().text());if(!productName||!price)return;const href=row.find("a[href]").first().attr("href"),status=compact(row.attr("data-status")??row.find(".status").text()),condition=normalizeCondition(row.attr("data-condition")??row.find(".condition").text());items.push({externalId:optional(row.attr("data-id")),productName,jan:optional(row.attr("data-jan")??row.find(".jan").text().replace(/\D/g,"")),modelNumber:optional(row.attr("data-model")??row.find(".model-number").text()),condition,price,buybackStatus:/停止|不可|休止/.test(status)?"paused":"accepting",productUrl:href?new URL(href,baseUrl).toString():undefined,fetchedAt});});return items;}

type Detail={allGoodsKbDetailId?:unknown;kbDetailName?:unknown;kbDetailPrice?:unknown};type Rel={keitaiKbDetailId?:unknown;varPrice?:unknown};type Color={jan?:unknown;keitaiKbDetailColorRels?:unknown};type ApiItem={goodsId?:unknown;allGoodsKbId?:unknown;title?:unknown;jan?:unknown;goodsKbDetails?:unknown;keitaiColorOptions?:unknown};
export function parseKaitori1ChomePayload(payload:unknown,baseUrl:string,fetchedAt:string):RawBuybackItem[]{if(!payload||typeof payload!=="object")return[];const content=(payload as {data?:{content?:unknown}}).data?.content;if(!Array.isArray(content))return[];const items:RawBuybackItem[]=[];for(const raw of content as ApiItem[]){const productName=typeof raw.title==="string"?compact(raw.title):"",details=Array.isArray(raw.goodsKbDetails)?raw.goodsKbDetails as Detail[]:[],colors=Array.isArray(raw.keitaiColorOptions)?raw.keitaiColorOptions as Color[]:[];if(!productName)continue;const unopened=details.filter(detail=>typeof detail.kbDetailName==="string"&&/未開封|新品未開封/.test(detail.kbDetailName));const variants=colors.length?colors:[{jan:raw.jan,keitaiKbDetailColorRels:[]}];for(const variant of variants){for(const detail of unopened){const base=Number(detail.kbDetailPrice),rels=Array.isArray(variant.keitaiKbDetailColorRels)?variant.keitaiKbDetailColorRels as Rel[]:[],adjustment=rels.find(rel=>Number(rel.keitaiKbDetailId)===Number(detail.allGoodsKbDetailId))?.varPrice,price=base+Number(adjustment??0);if(!Number.isSafeInteger(price)||price<=0)continue;const jan=typeof variant.jan==="string"?variant.jan:undefined,id=String(raw.goodsId??"");items.push({externalId:id?`${id}:${jan??"default"}:new`:undefined,productName,jan,condition:"new",price,buybackStatus:"accepting",productUrl:id?new URL(`/productDetail/${id}/${raw.allGoodsKbId??""}`,baseUrl).toString():undefined,fetchedAt});}}}return items;}
